### PR TITLE
[Feature]: add ScrollBody and ScrollOverlay demos for Dialog

### LINKED ISSUE #73: [Feature]: update Dialog to make it scrollable vertically if the content is larger
### Describe the feature

Make the content scrollable, using https://www.radix-vue.com/components/dialog.html

```
<script setup lang="ts">
import { defineProps, defineEmits } from "vue";
import {
  DialogClose,
  DialogContent,
  type DialogContentEmits,
  type DialogContentProps,
  DialogOverlay,
  DialogPortal,
} from "radix-vue";
import { X } from "lucide-vue-next";
import { cn, useEmitAsProps } from "../frameworkUtils";

const props = defineProps<DialogContentProps & { class?: string }>();
const emits = defineEmits<DialogContentEmits>();

const emitsAsProps = useEmitAsProps(emits);
</script>

<template>
  <DialogPortal>
    <DialogOverlay
      class="fixed inset-0 grid place-items-center z-50 bg-background/80 backdrop-blur-sm data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 overflow-y-auto"
    >
      <DialogContent
        :class="
          cn(
            'z-50 grid place-items-center w-full max-w-lg gap-4 border border-border bg-background p-6 shadow-lg duration-200 data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[state=closed]:slide-out-to-left-1/2 data-[state=closed]:slide-out-to-top-[48%] data-[state=open]:slide-in-from-left-1/2 data-[state=open]:slide-in-from-top-[48%] sm:rounded-lg md:w-full',
            props.class
          )
        "
        v-bind="{ ...props, ...emitsAsProps }"
      >
        <slot />

        <DialogClose
          class="absolute top-3 right-3 p-0.5 transition-colors rounded-md hover:bg-secondary"
        >
          <X class="w-4 h-4" />
          <span class="sr-only">Close</span>
        </DialogClose>
      </DialogContent>
    </DialogOverlay>
  </DialogPortal>
</template>
```

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

### PR DESCRIPTION
**Pull request by hrynevychroman**
this PR closes #73

### CODE REVIEW

**Comment by sadeghbarati** [comment]
before creating any branch make sure you have latest changes on your origins

image

**Comment by hrynevychroman** [comment]
Don't know why I have 3 commits, always make changes in new branches 🤔 

image

**Comment by sadeghbarati** [comment]
Discard those changes, and sync fork, don't worry

**Comment by hrynevychroman** [comment]
ok, I will update this PR to all changes from `dev` branch)

**Comment by hrynevychroman** [comment]
@sadeghbarati ready for review ❤️

**Comment by sadeghbarati** [comment]
Wops Zernonia changes are still here

I'll explain my way of creating PR 


- Always check my origin (my fork) and see if upstream (shadcn-vue) is ahead of me or not

- Sync fork, sometimes Discard changes and Sync together

- Switch to my dev branch ---> git pull

- Create a new branch in my IDE based on my `origin/dev`


---

Create a new PR if you are not familiar with git commands like me 😁

**Comment by hrynevychroman** [comment]
ok, i will make a new PR, thanks

**Comment by sadeghbarati** [comment]
@romanhrynevych 

Can you add me to your fork?

Your Repository ---> Settings ---> Collaborators

**Comment by hrynevychroman** [comment]
Send invite to you, I have 4 commits on dev branch, that are magically removed from this repo, don't know how to delete them, ahahaha 😂

**Comment by sadeghbarati** [comment]
Did something funny 😆 

`dev-fresh` is added now 

make it default and remove previous `dev` branch

after removing, rename `dev-fresh` to `dev` again 🤣

**Comment by hrynevychroman** [comment]
I do `sync` yesterday, I think that zernonia pushed this 3 commits, but then deleted them 🤔 
image

**Pull request closed without merging**
