### PR TITLE
Update components-json.md

### PR DESCRIPTION
**Pull request by jonathanwilke**
Add docs for aliases.ui

### CODE REVIEW

**Comment by sadeghbarati** [comment]
Many Thanks :heart:

Also sorry for forgetting to add this part to the docs 🙏

**Comment by jonathanwilke** [comment]
No problem man! You are doing amazing work here for free, so glad when I can support you in some way!

**Comment by sadeghbarati** [comment]
I would support Zernonia cause he is adding most of these great features, and Thanks for your kind words mean a lot 🙏

**Comment by jonathanwilke** [comment]
My company [supastarter](https://supastarter.dev) is already sponsoring this project 🚀

**Pull request merged**
