### PR TITLE
fix (app): dark mode bug

### LINKED ISSUE #78: [Bug]: Dark mode not working
### Environment

```bash
Development OS: Windows 10 
Node version: v16.19.0
Package manager: npm@8.19.2
Shadcn Vue version:shadcn-vue@0.1.9
Vue version: ^3.3.4
```

### Link to minimal reproduction

none

### Steps to reproduce
```
<template>
  dark
  <DashBoard/>
</template>
```

### Describe the bug

Hi, I noticed a strange behavior.

In my index.html, I manually added the class dark. Then, I ran npm run dev, expecting it to enable dark mode. However, the background remained white, indicating that dark mode was not working.

```
<!DOCTYPE html>
<html lang="en" class="dark">
```

To resolve this, I added the text 'dark' after an HMR (Hot Module Replacement) update. After this change, dark mode started working, and the background turned dark. I'm not sure what went wrong, but it seems I had to add the 'dark' text to my template.

App.vue

```
<template>
  dark
  <DashBoard/>
</template>
```

### Expected behavior

The dark mode should work if I add a dark class to the HTML tag

### Conext & Screenshots (if applicable)

_No response_

### PR DESCRIPTION
**Pull request by selemondev**
This pull request is intended to solve issue #78 

Closes #78

### CODE REVIEW

**Comment by sadeghbarati** [comment]
@selemondev 

Thanks for PR

After testing shadcn-vue in fresh Nuxt project found out it's about tailwind.config['content']
You should include `tailwind.css` (main shadcn file for tailwindcss) file in tailwind content

---

- `nuxt.config`

With `@nuxtjs/tailwindcss` you can extend tailwind content in `nuxt.config.ts`, 
It has [predefined paths for important Nuxt directories](https://github.com/nuxt-modules/tailwindcss/blob/main/src/resolvers.ts#L25C1-L35C3) like `layouts`, `pages`, `composables`, `plugins`, `utils`, ...

So you don't need to define them again in tailwind.config file


```ts
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  modules: ['@nuxtjs/tailwindcss', '@vueuse/nuxt'],
  devtools: { enabled: true },
  components: [
    {
      path: '~/components/ui',
      // this is required else Nuxt will autoImport `.ts` file
      extensions: ['.vue'],
      // prefix for your components, eg: UiButton
      prefix: 'Ui'
    },
  ],
  tailwindcss: {
    config: {
      content(content) {
        return [
          ...content, // https://github.com/nuxt-modules/tailwindcss/blob/main/src/resolvers.ts#L25C1-L35C3
          './assets/css/tailwind.css',
        ]
      },
      
      // or
      // content: ['./assets/css/tailwind.css']
     // not working with tsconfig paths like ~/assets/css/tailwind.css
    },
  }
})
``` 

https://github.com/radix-vue/shadcn-vue/assets/17789047/8e6be759-f639-43fd-8de6-ba7646b54416


---

- `vite`

Same as Nuxt but you have to extend and include `tailwind.css` file in your tailwind.config `content`

**Comment by sadeghbarati** [comment]
This should be documented I'll create PR for Vite and Nuxt sections

**Comment by selemondev** [comment]
@sadeghbarati My pull request solves the Vite-Vue issue described by @ezekel on issue #119 , whereby the dark mode doesn't work until you place a word.

**Comment by sadeghbarati** [comment]
I know but we should follow the same structure as [`shadcn-ui`](https://github.com/shadcn-ui/ui/blob/main/apps/www/styles/globals.css)

This issue can be fixed by `tailwind.config` itself without editing source files

**Pull request closed without merging**
