### PR TITLE
feat: `vue-input-otp`

### PR DESCRIPTION
**Pull request by sadeghbarati**

### CODE REVIEW

**Comment by zernonia** [comment]
Why `vue-input-otp`, does the one from `radix-vue` not fitting? 🤔 

it's basically the same as [PinInput](https://www.shadcn-vue.com/docs/components/pin-input.html)

Futhermore, adding more external packages always worries me with the integration with styling and js transformation.

**Comment by zernonia** [comment]
noticed a bug yaa.. seems like clicking on other input doesn't focus on them.. need to click multiple time then only able to focus other.

https://github.com/radix-vue/shadcn-vue/assets/59365435/07615058-37c3-4296-b9de-78ec1371080d

**Comment by sadeghbarati** [comment]
https://github.com/wobsoriano/vue-input-otp/issues/9

**Comment by wobsoriano** [comment]
Hey, I'm excited for this! Just a heads up - I saw a branch in the original repo and I think he's about to add in support for Svelte and Vue so I think the `vue-input-otp` package will likely be deprecated in favor of that soon.

https://github.com/guilhermerodz/input-otp/tree/feat/multi-frameworks/lib

cc @guilhermerodz

**Comment by guilhermerodz** [comment]
hey @wobsoriano a vuejs + svelte version is on input-otp roadmap.

I'll wait for the react lib to become stable (no significant issues opened in ~10-15 days) and then finally start working in the vanilla JS core so that we can export to another libraries such as vuejs and svelte. how does that sound?

**Comment by wobsoriano** [comment]
@guilhermerodz that sounds like a plan! For the meantime, I'll keep the `vue-input-otp` package in sync with the React version until your Svelte and Vue versions are released :) Once they're ready, I'll gladly include a link to your repository.

**Pull request closed without merging**
