### PR TITLE
docs: improve the installation section for each component

### LINKED ISSUE #31: [Feature]: Improve the `Installation` section for each components
### Describe the feature

Currently in  https://www.shadcn-vue.com/docs/components/avatar.html#installation only shows the CLI installation, however some components has more steps to that. eg `Accordion`.

Let's update all the `Installation` section for components 😁

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

### PR DESCRIPTION
**Pull request by selemondev**
This pull request is intended to close issue #31 by improving the installation section for each component.

### CODE REVIEW

**Comment by zernonia** [comment]
Thanks @selemondev ! However some component has more informantion need to be added. Please look at the image below ya 

image

**Comment by selemondev** [comment]
Of course! Can I be in charge of finishing up the Shadcn-Vue documentation site?

**Comment by zernonia** [comment]
Abolsutely! What do you have in mind that still need to be work on?

**Comment by selemondev** [comment]
Here is what can be improved:

1. The installation for each component.

2. Examples using the correct import paths.

Since Shadcn-Vue is a port of Shadcn-UI, we could include all the examples present in the Shadcn-UI documentation.

**Comment by selemondev** [comment]
I am working on this, I will create a PR soon.

**Comment by selemondev** [comment]
Done 🎉

**Comment by zernonia** [comment]
Thanks for the PR @selemondev ! I will merge this in, however there's some changes I will push to update some docs ya

**Comment by selemondev** [comment]
> Thanks for the PR @selemondev ! I will merge this in, however there's some changes I will push to update some docs ya

You are welcome and sure, no problem.

**Pull request merged**
