### PR TITLE
Update Calendar.vue to fix alignment

### LINKED ISSUE #343: [Bug]: The Calendar's Saturday and Sunday are not aligned
### Reproduction

https://www.shadcn-vue.com/docs/components/calendar.html

### Describe the bug

Hi,

I noticed Saturday and Sunday are not aligned.

I wondered if this was simply my locale (e.g Monday being first) however I tried adjusting the day of the week (from the VCalendar docs) and they still look wrong.

_Or_ perhaps it's because the original Shadcn uses a React-based library which defaults to using two-letters for each day.

Screenshot 2024-02-14 at 17 09 34

### System Info

```bash
System:
 OS: macOS 14.1.1
Binaries:
 Node: 20.11.0 - /usr/local/bin/node
 npm: 10.2.4 - /usr/local/bin/npm
 bun: 1.0.7 - ~/.bun/bin/bun
Browsers:
 Chrome: 121.0.6167.184
 Safari: 17.1
```

### Contributes

- [X] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

### PR DESCRIPTION
**Pull request by gregmsanderson**
The Calendar component's CSS adds additional padding which results in Saturday and Sunday not being aligned with the rest of the days.

This appears to fix: https://github.com/radix-vue/shadcn-vue/issues/343

calendar-without-additional-styles

### CODE REVIEW

**Comment by hrynevychroman** [comment]
Thanks for your PR, great 👍

**Comment by sadeghbarati** [comment]
Strange, those changes you removed used to prevent some other issues, which now cause problems 🤔

Will review tomorrow. Thanks

**Comment by gregmsanderson** [comment]
@sadeghbarati Ah. Hmm.

I think it needs _a_ fix but perhaps this isn't the _correct_ fix 🤔. The original shadcn didn't appear to be applying additional padding either ... but then they aren't using vcalendar which may have its own ideas.

**Comment by sadeghbarati** [comment]
Noticed `vc-weekdays` ~~default style~~ `vc-weeks > div` is using `grid` but in our style, we applied `flex` to it
Just added `justify-items-center` to `vc-weekdays` and cleared other paddings

**Pull request merged**
