### PR TITLE
fix(cli): missing props/emits when doesn't enable typescript

### LINKED ISSUE #62: [Bug]: Javascript has empty props/emits
Since `v0.1.6`, we've introduce [detype](https://github.com/cyco130/detype) to purge off all types related code in components.
However this leads to components having empty props/emits declarations.

Unfortuantely this would required a huge refactors on all the components.

### PR DESCRIPTION
**Pull request by Dunqing**
close: #62

Since the author left it unaddressed for a long time, and in case Javascipt users long time to use, I publish a [detypes](https://www.npmjs.com/package/detypes) package to temporarily fix the problem.

### CODE REVIEW

**Comment by zernonia** [comment]
Thanks for the hard work @Dunqing ! Could you add a simple test case for this transformation? 😁

**Comment by Dunqing** [comment]
> Thanks for the hard work @Dunqing ! Could you add a simple test case for this transformation? 😁

Sure, I added

**Comment by sadeghbarati** [comment]
Tested your branch, `pnpm build` cli and `pnpm start add button`



Button.vue
```vue
<script setup>
import { buttonVariants } from '.'
import { cn } from '@/lib/utils'

withDefaults( // <=== this API is typescript related
  defineProps({
    variant: { type: null, required: false },
    size: { type: null, required: false },
    as: { type: String, required: false, default: 'button' },
  }),
  {
    as: 'button',
  },
)
</script>

<template>
  <component
    :is="as"
    :class="cn(buttonVariants({ variant, size }), $attrs.class ?? '')"
  >
    <slot />
  </component>
</template>
```

---

Also tested with `npm link` for using cli outside of the project in fresh vite `template-vue`

```
> shadcn-vue add alert-dialog
√ Ready to install components and dependencies. Proceed? ... yes
- Installing components...Cannot read properties of undefined (reading 'sys') // error
```

When `jsconfig.json` is not present 

```
ENOENT: no such file or directory, stat 'vue-template/jsconfig.json' // error
```

**Comment by Dunqing** [comment]
> Tested your branch, `pnpm build` cli and `pnpm start add button`
> 
> Button.vue
> 
> ```
> <script setup>
> import { buttonVariants } from '.'
> import { cn } from '@/lib/utils'
> 
> withDefaults( // <=== this API is typescript related
>   defineProps({
>     variant: { type: null, required: false },
>     size: { type: null, required: false },
>     as: { type: String, required: false, default: 'button' },
>   }),
>   {
>     as: 'button',
>   },
> )
> </script>
> 
> <template>
>   <component
>     :is="as"
>     :class="cn(buttonVariants({ variant, size }), $attrs.class ?? '')"
>   >
>     <slot />
>   </component>
> </template>
> ```
> 
> Also tested with `npm link` for using cli outside of the project in fresh vite `template-vue`
> 
> ```
> > shadcn-vue add alert-dialog
> √ Ready to install components and dependencies. Proceed? ... yes
> - Installing components...Cannot read properties of undefined (reading 'sys') // error
> ```
> 
> When `jsconfig.json` is not present
> 
> ```
> ENOENT: no such file or directory, stat 'vue-template/jsconfig.json' // error
> ```

Thank you for testing this PR! Yes, I forgot the case with `withDefautls`, I fixed it in https://github.com/Dunqing/detype/commit/add6e46ef1a6882da53a2a2f010765a13f578272.

**Comment by Dunqing** [comment]
@sadeghbarati Can you take a look at it again? Thank you

**Comment by sadeghbarati** [comment]
#### `shadcn-vue add button` ✅ 

```vue
<script setup>
import { buttonVariants } from ".";
import { cn } from "@/lib/utils";

defineProps({
  variant: { type: null, required: false },
  size: { type: null, required: false },
  as: { type: String, required: false, default: "button" },
});
</script>

<template>
  <component
    :is="as"
    :class="cn(buttonVariants({ variant, size }), $attrs.class ?? '')"
  >
    <slot />
  </component>
</template>

```

---

#### `shadcn-vue add alert-dialog` ❌ 

```
shadcn-vue add alert-dialog

√ Ready to install components and dependencies. Proceed? ... yes
- Installing components...[@vue/compiler-sfc] No fs option provided to `compileScript` in non-Node environment. File system access is required for resolving imported types.

anonymous.vue
2  |  import { type AlertDialogEmits, type AlertDialogProps, AlertDialogRoot, useForwardPropsEmits } from 'radix-vue'
3  |
4  |  const props = defineProps<AlertDialogProps>()
   |                            ^^^^^^^^^^^^^^^^
5  |  const emits = defineEmits<AlertDialogEmits>()
```

**Comment by Dunqing** [comment]
> √ Ready to install components and dependencies. Proceed? ... yes
> - Installing components...[@vue/compiler-sfc] No fs option provided to `compileScript` in non-Node environment. File system access is required for resolving imported types.
> 
> anonymous.vue
> 2  |  import { type AlertDialogEmits, type AlertDialogProps, AlertDialogRoot, useForwardPropsEmits } from 'radix-vue'
> 3  |
> 4  |  const props = defineProps<AlertDialogProps>()
>    |                            ^^^^^^^^^^^^^^^^
> 5  |  const emits = defineEmits<AlertDialogEmits>()
> ```

Oh, This case seems hard to fix. Even if I pass `fs` in, it doesn't work, I can't get `radix-vue` as the real path.

**Comment by Dunqing** [comment]
Now it's supported! Do you @sadeghbarati  have time to test again? I have tested it, Looks good!  
image

**Comment by sadeghbarati** [comment]
Sure thanks for your efforts ❤️

**Comment by sadeghbarati** [comment]
@Dunqing 

All good ❤️  but this 👇 which is happening in some component 

```diff
- const defineProps
+ const props = defineProps
```

**Comment by Dunqing** [comment]
> @Dunqing 
> 
> 
> 
> All good ❤️  but this 👇 which is happening in some component 
> 
> 
> 
> ```diff
> 
> - const defineProps
> 
> + const props = defineProps
> 
> ```

Thanks, I noticed that the test cases had this problem as well

**Comment by Dunqing** [comment]
> @Dunqing
> 
> All good ❤️ but this 👇 which is happening in some component
> 
> ```diff
> - const defineProps
> + const props = defineProps
> ```

Fixed

**Review by sadeghbarati — APPROVED** [review]

**Comment by zernonia** [comment]
Absolute amazing work @Dunqing ! Thanks for taking on this difficult challenge!
@sadeghbarati  thanks for the review!

**Review by zernonia — APPROVED** [review]
LGTM! ❤️

**Pull request merged**
