### PR TITLE
fix(popover): add max-height to SelectContent (#263)

### LINKED ISSUE #263: [Bug]: Popover max-height need to be limited by available height
### Environment

```bash
Main Website
```

### Link to minimal reproduction

https://www.shadcn-vue.com/examples/cards

### Steps to reproduce

Just open Year Select on left card

image

### Describe the bug

Select don't limit by available height 🙂 

### Expected behavior

Need to add height, or max-height (think that max-height is better) to popover element, so scroll will be shown

image

### Conext & Screenshots (if applicable)

_No response_

### PR DESCRIPTION
**Pull request by hrynevychroman**
Closes: #263

### CODE REVIEW

**Comment by sadeghbarati** [comment]
Thank you, for spotting this

Can you apply the same change to the `default` style? not just `new-york` style

https://github.com/radix-vue/shadcn-vue/tree/dev/apps/www/src/lib/registry

**Comment by hrynevychroman** [comment]
Sorry, seen that in CONTRIBUTING but forget about it 😁 
image

**Review by sadeghbarati — APPROVED** [review]
🙌

**Comment by romanhrynevych** [comment]
This PR closes #101 too 🙂

**Pull request merged**
