### PR TITLE
feat: add `vee-validate`

### LINKED ISSUE #51: [Feature]: Form Component
### Describe the feature

Add the `Form` component like shadcn/ui

Link : https://ui.shadcn.com/docs/components/form

### Additional information

- [X] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

### PR DESCRIPTION
**Pull request by sadeghbarati**
Use **existing** VeeValidate components like `Form`, `Field`(FormField) and `ErrorMessage`(FormMessage)

Other components are inspired by Shadcn

### CODE REVIEW

**Comment by sadeghbarati** [comment]
@ahmedmayara Hi 👋 

Feel free to work on this PR, if you have time! if you have a better implementation let me know 🙌

**Comment by ahmedmayara** [comment]
Sure I'll check it out, I didn't have time to work on it recently.

**Comment by sadeghbarati** [comment]
@zernonia 

Just followed the same structure as Shadcn source `(Select the theme for the dashboard)` and faced these errors in `AppearanceForm.vue`

```
1. Uncaught (in promise) DOMException: Failed to execute 'querySelector' on 'Document': '[for=1-form-item]' is not a valid selector.

2. runtime-dom.esm-bundler.js:1164 Uncaught (in promise) TypeError: Cannot set properties of null (setting '_assign')
```

1. [This line in `radix-vue`](https://github.com/radix-vue/radix-vue/blob/aacb3a29c266988529820ed4b138e2dffc3b510a/packages/radix-vue/src/RadioGroup/Radio.vue#L38)

**Comment by zernonia** [comment]
> @zernonia
> 
> Just followed the same structure as Shadcn source `(Select the theme for the dashboard)` and faced these errors in `AppearanceForm.vue`
> 
> ```
> 1. Uncaught (in promise) DOMException: Failed to execute 'querySelector' on 'Document': '[for=1-form-item]' is not a valid selector.
> 
> 2. runtime-dom.esm-bundler.js:1164 Uncaught (in promise) TypeError: Cannot set properties of null (setting '_assign')
> ```
> 
> 1. [This line in `radix-vue`](https://github.com/radix-vue/radix-vue/blob/aacb3a29c266988529820ed4b138e2dffc3b510a/packages/radix-vue/src/RadioGroup/Radio.vue#L38)

That's the first time I'm seeing this.. could you create a minimal repro and a ticket in radix-vue. I can get to it asap

**Comment by sadeghbarati** [comment]
Hard to repro can you switch to this branch? 🙏

**Comment by sadeghbarati** [comment]
Problems:

1. We have to fix this bug first in both `radix-vue` and `shadcn-vue` components #35 <br/>
1.1 normal attributes like `id`, `disabled`, `class`, [and so forth...](https://github.com/vuejs/core/blob/main/packages/runtime-dom/src/jsx.ts#L239C19-L239C19), should not be in `defineProps` if we don't need to **mutate/update** them inside the component, 
types of these attributes(HTMLAttributes) is handled by default with Vue `runtime.d.ts`

    [`useAttrs` is enough for these attributes](https://github.com/radix-vue/shadcn-vue/issues/35#issuecomment-1735232086)
    
    [More info here](https://play.vuejs.org/#eNrlVUtP20AQ/itTqxJBSuyi9pSGFGg5UKktohx92dgTe2G9a+2uAyjKf+/s+hHbAVSk3sqFeJ7fzuObbXBeluGmwmAeLEyieWnBoK3KZSx5USptYQsa17CDtVYFHJHp0edOd1FZq2SjCqP604U7sLmSEvUNssTyDbdPI5eR1keIZSwTJY2Flbf5xg1bCUzh1AGarJkweBzLRVTDJsD0YbEoBbNIXwCL2hHOEsGT+9M4OAj0biiJg+WtyjKBcG6t5qREA0rDtValgQdu8zGWGyoNuFyULeUbn9Z/rJbb7dB2t1tEq8ZgEbXGJPNWHj595rr91dR2njb+B/gJbR2ttqyj1b9fijbuwl8HHzn2c41U5LaIujYE08Aa6uKaZ+GdUZLGbOuc4yBRRckF6l+l5dTlOJiD1zgdE0I9fPcyqyuctvIkx+T+GfmdeXSyOLjWaFBvMA46nWU6Q1urL3//xEf63SkLlVaCrF9R3qBRonIYa7OLSqYEu2fn0V75YecyuzWXjxalaR/lgDrLnbePAxrtr688fQ/3Y/jR+8VyR1Xcr5bb1P2Y62agmimCxbvZDNY0s1Lpgglg+0GuDLqx9hP93skNcAMoVZXlwNdgc3wCppFcLa2YbygCp6ek6JTgWqYkSguzWZfZZzdC0QL2JP4xfYuoMxmIaQ1gM+Nrmr8aUthOpBvAUUBaqrHI/bUj29R67OSWboDEr94hCCQ+eXtKT0Nvy7lfeRIMd+VFNhzTMwgmMyqapenxcTqytoo4aQpK/lCVtJhO4YHZJB8ReK8PNceWnuJOIcU1l+gJb7Htv6Hty5c5rJQSyAaNJDdWCdvW5Xkj7uRMPrWy3XJyfIikTURg/FsmHtoUjlrF0TFEkTO2WglvuBzTsn9qc9mG0YViKW3pMHg4gu8TVO76NClalG0sX9JJC2gKkw0Txw7H1nk2u+MI9rnt6ZekgROSf4UEiv531RnUpuvnZFIn6kdxT6Nqh0JlHSjv/ZxBk7LT7/PsT2kreIlnBoejKeF+b2sS4jJHzW1NOUQ0nrFdoxzXPKmKylQoIpjXQrXDQLdXCM9LD0rfu/5RLbjwYWgfgP9DSspP6HR3c+KuNkn6Fi8R2H/NXDX/zApWju58rRgeuTNaS7pGUaJ0c3xza0szj6KMkXtZhFxFsizmfcOzkw/hp/Ak4jLFx7C4o5Ddfdz9ATBYdHY=)

---

2. You have to expose `useId` within `radix-vue` cause `vee-validate` FieldContext `id` is not enough for our case (duplicated IDs) 
or expose any other useful utilities in `radix-vue` shared directory instead of duplicated code in two repository

https://github.com/radix-vue/radix-vue/blob/aacb3a29c266988529820ed4b138e2dffc3b510a/packages/radix-vue/src/shared/useEmitAsProps.ts#L5
https://github.com/radix-vue/shadcn-vue/blob/2001d1be3f308227b557c1e9ed1cba03238ffc8a/apps/www/src/lib/utils.ts#L12

**Comment by zernonia** [comment]
Ahh that's brilliant!! I never thought of exposing useful utilities from `radix-vue`!!! I'm on it!

And yeah.. using class as props for components is not a good design.. we can create a ticket that replaces all the class props in `shadcn/vue`

**Comment by zernonia** [comment]
@sadeghbarati  Both of the ticket above had merged and released in `v0.4.0`. Do let me know if it helps 😁

**Comment by sadeghbarati** [comment]
@zernonia @ahmedmayara please review it 🙌 

---

```vue
<FormField v-slot="{ value }" name="language">
```

`value` slotProp types is `any` which Idk how to fix without **type narrowing**
maybe we could mention `vee-validate` author?

**Review by ahmedmayara — APPROVED** [review]
Looks good to me! 😁

**Comment by sadeghbarati** [comment]
Okay 😄  let's wait for `Toast` component #56

**Comment by zernonia** [comment]
Nicelt done @sadeghbarati ! Sorry missed out this ticket few days ago 😂 
Can we quickly add the `form.md`?

**Comment by sadeghbarati** [comment]
Ok will do 🫡

What about mentioning some differences of vee-validate 

- Difference between `field`(native inputs) and `componentField`(input components) in slotProps

- `Form` and `useForm`

- ~~`defineInputBinds` (native input elements) and `defineComponentBinds` (input components)~~ `defineXXXBinds` will be deprecated and will replaced with `defineField`

- `useFieldModel` deprecate❌ 
- `defineInputBinds` deprecate❌ 
- `defineComponentBinds` deprecate❌ 

- `defineField` ✅ 


Since my English is bad I may need help on form.md 🫠

**Comment by zernonia** [comment]
The PR looks freaking good @sadeghbarati !!! The docs for `form` looks good for now. 
In terms of the difference between different usage, we can add it in in the next PR.  😁

**Pull request merged**
