### PR TITLE
feat: improve cli from main shadcn-ui source, custom ui dir

### LINKED ISSUE #308: [Bug]: Duplicate tailwind classes with cssVariables: false which override others
### Environment

```bash
Developement/Production OS: Windows 11
Node version: 20
Package manager: pnpm@8.7.6
Radix Vue version: 1.3.2
Shadcn Vue version: 0.8.7
Vue version: 3.0.0
CSS framework: tailwindcss@3.4
```

### Link to minimal reproduction

https://stackblitz.com/edit/vitejs-vite-95bgnv?terminal=dev

### Steps to reproduce

- Go on the link (At this point, you can already see the `Checkbox` component)
- Open the terminal
- Run `npx shadcn-vue@latest add checkbox`
- Overwrite the component to see the generated component
- The component has classes which override others 

### Describe the bug

When I generate `Checkbox` component using the CLI with the next command: `npx shadcn-vue@0.8.7 add checkbox` or `npx shadcn-vue@latest add checkbox`
And I go to the generated `Checkbox` component
So I have duplicate tailwind classes which overrides another: `border-neutral-200` and `border-neutral-900` or `dark:border-neutral-800` and ` dark:border-neutral-50`.

I didn't test all components but the behavior is also true for `AlertDialogContent` component.

### Expected behavior

No tailwind classes which overrides another.

### Conext & Screenshots (if applicable)

_No response_

### PR DESCRIPTION
**Pull request by sadeghbarati**
close #308 

- removed unused deps
- bring custom ui dir and other cli improvements from shadcn-ui to here thanks to them
- bump deps which resolve this issue too https://github.com/radix-vue/shadcn-vue/issues/308
- used [`nypm`](https://github.com/unjs/nypm) for installing deps and detecting packageManager
- used [`consola`](https://github.com/unjs/consola) instead of logger function and `chalk` module
- used [`c12`](https://github.com/unjs/c12) instead of `cosmiconfig`

Sry for the bad commit messages I really don't know how to write a good commit message 😶‍🌫️

### CODE REVIEW

**Comment by zernonia** [comment]
Thanks for the PR and using those package from `unjs` @sadeghbarati ! It is so much easier to use!

One point to note tho.. I don't quite understand the idea of `ui` alias, do you have relevant PR from `shadcn-ui`?

**Comment by sadeghbarati** [comment]
looks like I have to ask a question about the c12 config loader in Nuxt Discord unjs section

- components.[json,json5,jsonc]
- components.[js,cjs,mjs]

currently, it's looking for `.json` cause we set  `configFile: 'components.json'`
but with `configFile: false` I have this error

```
Error: EISDIR: illegal operation on a directory, read
```

https://x.com/_pi0_/status/1755506422274523641?s=20
https://github.com/unjs/c12

**Comment by sadeghbarati** [comment]
@zernonia 

With this https://github.com/radix-vue/shadcn-vue/pull/324/commits/4762c673763af301f5c7515910d10e1313423e42 change `c12` will look for every supported extension that it has 
but `json5` has a bug that will be resolved after my PR gets merged to c12 repository

---

Only this 👉   utility is **missing** in our CLI **`(tw-prefix)`**, which Idk how to solve cause I did not work with AST parsers like `oxc-parser`, `ts-morph`, or `magic-string`

Also, how to remove duplicated AST parsers and use one of them

https://github.com/shadcn-ui/ui/blob/main/packages/cli/src/utils/transformers/transform-tw-prefix.ts

**Comment by zernonia** [comment]
Thanks @sadeghbarati ! I can help look at `tw-prefix` 😁

**Comment by zernonia** [comment]
@sadeghbarati  added the `tw` prefix feature to CLI. Do have a look! If it's all good then we can merge! 😁

**Review by zernonia — APPROVED** [review]

**Comment by zernonia** [comment]
@sadeghbarati  the `prefix` need more work.. I've temporary hide the config. I think we can merge this in and have another PR for the `prefix`

**Comment by msyfls123** [comment]
Want to know further information of recovering `prefix` option, actually I really need this option.
Plz 🙏🏻

**Comment by zernonia** [comment]
@sadeghbarati  can you create an issue for adding `prefix`? 😁  Maybe someone can help contribute to this

**Pull request merged**
