### PR TITLE
feat: new calendar components

### PR DESCRIPTION
**Pull request by sadeghbarati**
Thanks to Eduard Predescu for his ongoing work on RadixVue Calendar ❤️

### CODE REVIEW

**Comment by sadeghbarati** [comment]
I'll try to update docs and add more examples for Calendar and Other Components and also remove "New" labels from old components in `docs.ts` (side nav), after this PR

**Comment by sadeghbarati** [comment]
Waiting for new calendar fixes to be released after that we can merge this ✨

**Review by zernonia — APPROVED** [review]
LGTM @sadeghbarati !!!!

**Comment by zernonia** [comment]
@sadeghbarati We can merge this! Also, let's remove those "new" tag for other components 😁

**Pull request merged**
