### PR TITLE
feat: add number-field component

### PR DESCRIPTION
**Pull request by romanslonov**
Hello, 

I have implemented this feature #567.

https://github.com/radix-vue/shadcn-vue/assets/10784316/e313d469-3688-464c-b107-423909c4f947

This is my first take. Let's discuss it.

**upd:**
I found a bug that seems to be when you completely erase the value of an input that is in the form, type a new value and if you press enter, the form will be submitted but the value is not updated, the value will only be updated on the blur event. You can find same behaviour on radix-vue preview page of this component. `<NumberFieldInput @keydown.enter.prevent />` this fix the issue though.

### CODE REVIEW

**Comment by sadeghbarati** [comment]
@romanslonov Thanks for the PR, next time please create new branch for your PRs 

---

Everything looks good to me in Number Field except this behaviour in Number Field input, @zernonia 

- Manually update Number Field value
- Hit up and down arrows to update the value

https://github.com/radix-vue/shadcn-vue/assets/17789047/e9f05d18-0091-4e70-ad16-245f94095880

**Comment by zernonia** [comment]
Thanks for the PR @romanslonov ! 
Thanks @sadeghbarati  for catching that. Will create an issue for that.

Also, I kinda regret adding `NumberFieldLabel` component lol 😅, as it would required additional configuration if dev wanna use it with `AutoForm`, which will generate the label automatically.

**Comment by romanslonov** [comment]
> Also, I kinda regret adding `NumberFieldLabel` component lol 😅, as it would required additional configuration if dev wanna use it with `AutoForm`, which will generate the label automatically.

Yes, what if you remove `NumberFieldLabel` component and let users to use common `<Label />` similar as we do it for `<Input />`, `<Textarea />` etc.

**Comment by zernonia** [comment]
> > Also, I kinda regret adding `NumberFieldLabel` component lol 😅, as it would required additional configuration if dev wanna use it with `AutoForm`, which will generate the label automatically.
> 
> Yes, what if you remove `NumberFieldLabel` component and let users to use common `<Label />` similar as we do it for `<Input />`, `<Textarea />` etc.

Yup that's what I should've done hahaha.. Since the `NumberFieldLabel` is just wrapper for `Label` anyway.

**Comment by romanslonov** [comment]
> > > Also, I kinda regret adding `NumberFieldLabel` component lol 😅, as it would required additional configuration if dev wanna use it with `AutoForm`, which will generate the label automatically.
> > 
> > 
> > Yes, what if you remove `NumberFieldLabel` component and let users to use common `<Label />` similar as we do it for `<Input />`, `<Textarea />` etc.
> 
> Yup that's what I should've done hahaha.. Since the `NumberFieldLabel` is just wrapper for `Label` anyway.

I will submit a PR to radix-vue to remove it, and then update this PR as well

**Comment by sadeghbarati** [comment]
Let's wait for new Number Field fixes to be released, then we can merge this

**Pull request merged**
