### PR TITLE
fix: `new-york` demos are using the incorrect icon library

### LINKED ISSUE #403: [Bug]: Some StackBlitz New-York demos are using the incorrect icon library
### Reproduction

https://stackblitz.com/run?file=src%2FApp.vue

### Describe the bug

When running component demos on StackBlitz with the `new-york` style option, it throws the following error: `[plugin:vite:import-analysis] Failed to resolve import "lucide-vue-next" from "src/App.vue". Does the file exist?`

Issue: Some of the `new-york` demos are still trying to use Lucide icons instead of Radix.

### System Info

```bash
Running on the Stackblitz demo clicked via the Shadcn/vue documentation site.
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

### PR DESCRIPTION
**Pull request by sadeghbarati**
close #403

Add hard-coded solution for `new-york` based on `default` examples

### CODE REVIEW

**Comment by zernonia** [comment]
hmmm.. don't think we need to hardcode it.. adding another function parameter to deterermine `default/new-york` should do.

**Comment by sadeghbarati** [comment]
Can you explain please?

```
import ComponentPreviewPlugin from './theme/plugins/previewer'
```

`previewer.ts` is a custom markdown plugin how can I make it dynamic on client-side `style` switcher

**Comment by zernonia** [comment]
@sadeghbarati  do you mind if I handle this? Perhaps wanna refactor to enable https://github.com/radix-vue/shadcn-vue/issues/146#issuecomment-1819599224 as well 😁

**Comment by sadeghbarati** [comment]
Sure cause I don't know how to handle those 😅🙌

**Comment by zernonia** [comment]
closing this in favor of https://github.com/radix-vue/shadcn-vue/pull/411 . Thanks @sadeghbarati  nonetheless! 😁

**Pull request closed without merging**
