### PR TITLE
feat(cli): support `tailwind.config.mjs` file

### PR DESCRIPTION
**Pull request by Dunqing**
When the extension of the tailwind configuration file is mjs, transform cjs syntax to esm syntax.

If I understand it right, we just need to handle tailwind.config.mjs file correctly in `astro` framework? 
cc @sadeghbarati @selemondev

### CODE REVIEW

**Comment by sadeghbarati** [comment]
Yes, Right `@astrojs/tailwind>=@5.0.2` integration will create `tailwind.config.mjs`

https://github.com/withastro/astro/blob/main/packages/integrations/tailwind/CHANGELOG.md#502

**Comment by sadeghbarati** [comment]
Can I push some changes? @Dunqing

**Comment by Dunqing** [comment]
> Can I push some changes? @Dunqing 

Sure！

**Comment by zernonia** [comment]
Thanks for the PR @Dunqing  @sadeghbarati ! However seems like the Test in the pipeline has failed. Could you check on that? 😁

**Comment by Dunqing** [comment]
> Thanks for the PR @Dunqing @sadeghbarati ! However seems like the Test in the pipeline has failed. Could you check on that? 😁

Done

**Pull request merged**
