### PR TITLE
feat: add `pinia` and `pinia-shared-state` for sync shared state between tabs

### PR DESCRIPTION
**Pull request by sadeghbarati**
States like

- Color
- Radius
- Style

### CODE REVIEW

**Comment by zernonia** [comment]
curious what was the reason to use pinia 🤔

**Comment by sadeghbarati** [comment]
You were using `@vueuse/core` `useSession` for states
Every `Browser Tab` has its own session and states are not shared across tabs

**Comment by sadeghbarati** [comment]
Kinda related https://github.com/radix-vue/shadcn-vue/issues/146

I was working on adding custom alias (`@/components/`) in https://www.shadcn-vue.com/themes.html (Customize Button) but could only handle changing aliases in `<ComponentPreview>` component, not in rendered markdowns 

then I tried sharing other states

**Comment by zernonia** [comment]
we can just swap it with `useLocalStorage` lol. I dont think we need full-fledged state management for this tiny config store


https://github.com/radix-vue/shadcn-vue/assets/59365435/7c243afd-a725-4e31-9704-35db92f89aac

**Comment by sadeghbarati** [comment]
You right 😂

For Aliases I thought better to turn it back to default alias when user close all shadcn-vue tabs 

btw I removed dynamic alias implementation before pusing changes 😭😁

feel free to close 🫡

**Pull request closed without merging**
