### PR TITLE
fix: class typo

### LINKED ISSUE #96: [Bug]: Typo in tailwind classes
https://github.com/radix-vue/shadcn-vue/blob/223583b2171a898d9b875a53167f295d7f59062b/apps/www/src/lib/registry/default/ui/avatar/index.ts#L8C1-L8C1

`text-foregorund` should be `text-foreground`

### PR DESCRIPTION
**Pull request by MuhammadM1998**
Fixes #96

### CODE REVIEW

**Review by zernonia — CHANGES_REQUESTED** [review]
I realized the typo happen in `apps/www/src/lib/registry/new-york/ui/avatar/index.ts` too. Let's change it too ya!

**Comment by MuhammadM1998** [comment]
They are on these paths too. Are those automatically generated or should we change it too?
`apps/www/src/public/registry/styles/default/avatar.json`
`apps/www/src/public/registry/styles/new-york/avatar.json`

**Comment by zernonia** [comment]
those `.json` are generated automatically. so need not to change those

**Review by zernonia — APPROVED** [review]
lgtm!

**Comment by zernonia** [comment]
thanks for your contribution @mukundshah  😁

**Pull request merged**
