### PR TITLE
fix: checkbox icon off-center fix

### PR DESCRIPTION
**Pull request by bgervan**
The checkbox was off-center

### CODE REVIEW

**Comment by sadeghbarati** [comment]
Just found kinda of the same title in the main `shadcn-ui` PRs

https://github.com/shadcn-ui/ui/pull/1935/files

Can you edit your PR according to the Tomasmenezes PR in `shadcn-ui`?

**Comment by bgervan** [comment]
> Just found kinda of the same title in the main `shadcn-ui` PRs
> 
> https://github.com/shadcn-ui/ui/pull/1935/files
> 
> Can you edit your PR according to the Tomasmenezes PR in `shadcn-ui`?

Updated

**Review by sadeghbarati — APPROVED** [review]
🙌

**Comment by sadeghbarati** [comment]
Updated SVG sizes (`element.style` devtools) to `150x150` (**ignore** h-4 and w-4 in images) 
Also make their parent element bigger to show what is this PR doing

<details><summary>Before</summary>
<p>

image


</p>
</details> 


<details><summary>After</summary>
<p>

image


</p>
</details>

**Pull request merged**
