### PR TITLE
fix: Calendar transition bug

### LINKED ISSUE #126: [Bug]: Calendar & Date picker: glitch/flickering when jumping through months
### Environment

```bash
Computer: MacBook Pro 2021 M1
Client OS: MacOs Monterey 12.6.1 (21G217)
Browser: Firefox Dev 117.0b9, Chrome 116.0.5845.110, Safari 15.6.1 (17613.3.9.1.16)
```

### Link to minimal reproduction

Official docs

### Steps to reproduce

Visit [https://www.shadcn-vue.com/docs/components/date-picker#form](https://www.shadcn-vue.com/docs/components/date-picker#form) and click through 

### Describe the bug

Hey, I have a weird glitch or flickering when I'm clicking through the months. I've tried to capture/record it but since the display of my MBP M1 is probably running at 120Hz and the recording software runs at 60fps at max I can't actually show what it looks like. For a brief millisecond it shows the next/previous months below the current month and then vanishes right after. So it takes up the whole screen I'm showing in the picture.
It's happening with the Calendar and Datepicker component in Firefox Dev, Safari and Chrome. It does not happen when using VCalendar. So my best guess is that it's because of the transition that's supposed to fire but doesn't actually show? At least I'm not seeing any slide animation just a hard cut right after the glitch.

Does this help to narrow down what might be happening?
Thanks for the awesome port!

### Expected behavior

No flickering, smooth transition.

### Conext & Screenshots (if applicable)

https://github.com/radix-vue/shadcn-vue/assets/42282368/79e27f2a-b855-4d76-bac7-9e5e560a7349

### PR DESCRIPTION
**Pull request by lovlyx**
Added classes from VCalendar styles to fix transition glitch.

### CODE REVIEW

**Comment by sadeghbarati** [comment]
Can you share a video of your fix? Thanks 🫡🙌

**Comment by sadeghbarati** [comment]
The Glitch partially goes away but,
Main shadcn-ui [`Calendar`](https://ui.shadcn.com/docs/components/calendar) has no transition

---

https://github.com/radix-vue/shadcn-vue/assets/17789047/807a4755-2710-4653-8711-9b15b467e482

**Comment by lovlyx** [comment]
@sadeghbarati 

Old Calendar Transition:
https://github.com/radix-vue/shadcn-vue/assets/110987585/6e7030a4-fad0-4e20-8c99-ea4ecd0f22ac

Fixed Calendar Transition:
https://github.com/radix-vue/shadcn-vue/assets/110987585/f38a1735-d95f-4798-b7b6-2000c3f8798c

I've noticed on the new version there is still a trail that shows on the horizontal axis, but that could probably fixed with overflow-hidden.

**Comment by sadeghbarati** [comment]
Other maintainers should decide: "Keep transition for Calendar or make it like the main shadcn-ui"

IMO let's follow the main `shadcn-ui`, no transition
If other maintainer decide to keep transition I will rebase and drop my commit :pray:

**Comment by lovlyx** [comment]
Yeah, but we would have to find a fix for the glitches when moving pages.

**Comment by sadeghbarati** [comment]
find a way you can append these to style section

```css

.vc-pane-container {
  width: 100%;
  position: relative;
}

.vc-pane-container.in-transition {
  overflow: hidden;
}

.vc-slide-left-leave-active,
.vc-slide-right-leave-active {
  position: absolute !important;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  width: 100%;
  height: 100%;
}

.vc-slide-left-enter-from,
.vc-slide-left-leave-to,
.vc-slide-right-enter-from,
.vc-slide-right-leave-to {
  opacity: 0;
}
``` 

and add `z-10` to the `div` that **contains** this classes `absolute flex justify-between w-full px-4 top-3`

**Comment by sadeghbarati** [comment]
Can I push? @lovlyx

**Comment by sadeghbarati** [comment]
https://github.com/radix-vue/shadcn-vue/assets/17789047/8bb21543-433e-490e-a161-e67a3d177d46

**Comment by lovlyx** [comment]
Oh Perfect!

**Comment by zernonia** [comment]
Personally I would prefer the transition (although original `shadcn` doesn't). I felt smoother and keep consistent as most of the components with `entry/exit` component has transition.

**Comment by sadeghbarati** [comment]
@lovlyx 

I can't access to my computer right now can you drop my commit? 

If you not familiar with `vim`, change git editor to VSCode

```
git config --global core.editor "code --wait"
```

- git rebase -i HEAD~2 (interactive rebase last two commits)

- select drop
- git push --force-with-lease

Also, don't forget about overflow-hidden 


Thanks 🫡

**Comment by lovlyx** [comment]
Okay @zernonia it should all be good now.

**Review by zernonia — APPROVED** [review]
LGTM! Thanks @lovlyx  @sadeghbarati

**Pull request merged**
