### PR TITLE
Update CommandDialog.vue to add custom filter-function

### PR DESCRIPTION
**Pull request by maelp**
Add a custom filter-function to CommandDialog

### CODE REVIEW

**Review by hrynevychroman — APPROVED** [review]
Seems good)

**Comment by sadeghbarati** [comment]
@maelp can you add exact same changes to `new-york` style?

**Comment by sadeghbarati** [comment]
@romanhrynevych 

What is the difference between this PR and your PR in https://github.com/radix-vue/shadcn-vue/pull/284

**Comment by hrynevychroman** [comment]
@sadeghbarati I was trying to fix that TS error, but nothing helped at all, I see that in this PR maelp destructure filter function and provide it as props to `Command` component

Also, I don't think that it is a great idea to overlap default `radix-vue` props interface for Dialog, maybe change firstly it inside radix-vue and then test here?

This is type of errors depends on `radix-vue` codebase, not `shadcn-ui` at all 😢

**Comment by maelp** [comment]
@sadeghbarati I did the change for NY

**Comment by sadeghbarati** [comment]
I'm still not sure about this PR

The current Command (Combobox) in `radix-vue` has some problems adding a props to add another custom filter function is good? Idk

Maybe share a video (with open devtools) here to see what PR is about

---

https://github.com/xiaoluoboding/vue-command-palette

I'll try to make PR to `vue-command-palette` to update their deps then try port the pkg to `shadcn-vue` until `radix-vue` Command become ready

**Comment by sadeghbarati** [comment]
Let's wait for radix-vue `Listbox` implementation it should fix Combobox issues

**Pull request closed without merging**
