### PR TITLE
feat(components): add carousel dot buttons

### LINKED ISSUE #521: [Feature]: Dot Buttons for Carousel
### Adding Support for Dot Buttons in Carousel

The current Carousel does not support Dot Buttons. The library Embla Carousel supports the usage of dot buttons, as shown in this [React example](https://codesandbox.io/p/sandbox/embla-carousel-default-react-jrlnks). Can we add support for dot buttons?

Updates:
I think this setup for the carousel composable would work:
```js
import { createInjectionState } from '@vueuse/core';
import emblaCarouselVue from 'embla-carousel-vue';
import { onMounted, ref } from 'vue';

const [useProvideCarousel, useInjectCarousel] = createInjectionState(({ opts, orientation, plugins }, emits) => {
  const [emblaNode, emblaApi] = emblaCarouselVue(
    {
      ...opts,
      axis: orientation === 'horizontal' ? 'x' : 'y',
    },
    plugins
  );

  function scrollPrev() {
    emblaApi.value?.scrollPrev();
  }
  function scrollNext() {
    emblaApi.value?.scrollNext();
  }
  function scrollTo(index) {
    emblaApi.value?.scrollTo(index)
  }

  const canScrollNext = ref(true);
  const canScrollPrev = ref(true);
  const selectedIndex = ref(0);
  const scrollSnaps = ref([])

  function onSelect(api) {
    canScrollNext.value = api.canScrollNext();
    canScrollPrev.value = api.canScrollPrev();
    selectedIndex.value = api.selectedScrollSnap();
    scrollSnaps.value = api.scrollSnapList();
  }

  onMounted(() => {
    if (!emblaApi.value) return;

    emblaApi.value?.on('init', onSelect);
    emblaApi.value?.on('reInit', onSelect);
    emblaApi.value?.on('select', onSelect);

    emits('init-api', emblaApi.value);
  });

  return {
    carouselRef: emblaNode,
    carouselApi: emblaApi,
    canScrollPrev,
    canScrollNext,
    scrollPrev,
    scrollNext,
    scrollTo,
    scrollSnaps,
    selectedIndex,
    orientation,
  };
});

function useCarousel() {
  const carouselState = useInjectCarousel();

  if (!carouselState) throw new Error('useCarousel must be used within a <Carousel />');

  return carouselState;
}

export { useCarousel, useProvideCarousel };

```
And here would be my version of the dot "buttons"
```vue
<template>
  <div
    v-for="(item, index) in scrollSnaps"
    :key="index"
    class="sm:mt-0 first:ml-0 border-1 w-2 h-2 mt-2 ml-2 border-gray-200 border-solid rounded-full"
    :class="[cn(props.class), index === selectedIndex ? 'border-transparent bg-blue-400' : 'bg-transparent']"
    @click="scrollTo(index)"
  />
</template>
<script setup>
import { useCarousel } from '~/composables/carousel';
import { cn } from '~/lib/utils';

const props = defineProps({
  class: {
    type: String,
    default: '',
  },
});

const { scrollTo, selectedIndex, scrollSnaps } = useCarousel();
</script>
```

### PR DESCRIPTION
**Pull request by quankhuc**
Add dot buttons to carousel component based on the availablity of dot buttons in embla carousel vue.

### CODE REVIEW

**Comment by sadeghbarati** [comment]
IMO, this is too much, which can be added by the user

also, not working well with orientation. Carousel Dots should respect the orientation

**Comment by zernonia** [comment]
I think we can have this addition be part of the component. As it doesn't required much refactoring, and the `DotButtons` make sense. As @sadeghbarati  said let's make sure that it is respectively the orientation ya 😁

**Comment by quankhuc** [comment]
Thank for your suggestions! I will fix it so that it can look good with orientation

**Comment by quankhuc** [comment]
I have fixed the code to make it work with orientation. Please let me know what you think!

**Pull request closed without merging**
