### PR TITLE
Charting

### PR DESCRIPTION
**Pull request by zernonia**
- [x] Bar
- [x] Line
- [x] Area
- [x] Donut

### CODE REVIEW

**Comment by orenmizr** [comment]
🏆

**Comment by Veskel01** [comment]
@zernonia Is there any chance that the charts will come to the library ? They look amazing and it's a real shame that they have not been on the main branch until now

**Comment by zernonia** [comment]
Glad to hear you are looking forward to this @Veskel01 !  Still have some touchup and consideration to be made, and I'm kinda occupied elsewhere. 

However you are welcome to copy/paste the current code into your project if you wan 😁

**Comment by russssl** [comment]
> Glad to hear you are looking forward to this @Veskel01 ! Still have some touchup and consideration to be made, and I'm kinda occupied elsewhere.
> 
> However you are welcome to copy/paste the current code into your project if you wan 😁

so are charts stable enough to be used in projects?

**Comment by Celibioux** [comment]
Any updates on this one please ?

**Comment by orenmizr** [comment]
very excited about this pr. much appreciated

**Review by sadeghbarati — APPROVED** [review]
🔥

**Comment by Celibioux** [comment]
Great work @zernonia 🔥 really needed the charting tool even if i use radix-vue now i need shadcn-vue too ? XD

**Pull request merged**
