### PR TITLE
feat: tags input

### PR DESCRIPTION
**Pull request by sadeghbarati**
Can't figure out how to create `Multiple Combobox` with `TagsInput` can you do it in `TagsInputComboDemo.vue`? @zernonia 🙏  

https://183b3d8d.shadcn-vue.pages.dev/docs/components/tags-input

### CODE REVIEW

**Comment by zernonia** [comment]
Thanks @sadeghbarati . Using the current `Combobox` with `TagsInput` doesn't quite make sense. It's behave differernt as per the example in `radix-vue`.

I'm gonna try and compose a different demo of `TagsInput`

**Comment by zernonia** [comment]
Updated the demo. You can check it [here](https://1efca013.shadcn-vue.pages.dev/docs/components/tags-input.html) @sadeghbarati 

We just need to update the description abit then I think this PR is ready!

**Comment by sadeghbarati** [comment]
Nice changes ❤️ 

https://mui.com/material-ui/react-autocomplete/#multiple-values

I would rather 

- open `Combobox` or `Autocomplete` with `click` or `enter` on input or a trigger just like `ComboboxDemo` (chevron down)
- have 100% width dropdown
- prevent closing dropdown after select

**Comment by zernonia** [comment]
> Nice changes ❤️
> 
> https://mui.com/material-ui/react-autocomplete/#multiple-values
> 
> I would rather
> 
> * open `Combobox` or `Autocomplete` with `click` or `enter` on input or a trigger just like `ComboboxDemo` (chevron down)
> * have 100% width dropdown
> * prevent closing dropdown after select

@sadeghbarati  All these can be easily done 😉 Feel free to modify it!

**Comment by zernonia** [comment]
I purposely made  `ComboboxAnchor` anchor to the input because I like that 😂. You can move it to the wrap around the component to achieve full width.

**Review by zernonia — APPROVED** [review]
@sadeghbarati I've checked the `tagsInput` and LGTM. You can merge when ready

**Pull request merged**
