### PR TITLE
fix: make NumberField more flexible (#613)

### LINKED ISSUE #613: [Bug]: NumberField without Increment and Decrement
### Reproduction

https://codesandbox.io/p/devbox/shadcn-vue-numberfield-padding-xnwmrm

### Describe the bug

When removing `NumberFieldDecrement` and `NumberFieldIncrement` around `NumberFieldInput`, the input has large padding on both sides.

image

My temporary fix was to add `px-1` class to `NumberFieldInput` like so:
`<NumberFieldInput class="px-1" />`

The `NumberFieldInput` component must have a class prop to override the padding:
```
<script setup lang="ts">
import { NumberFieldInput } from 'radix-vue';
import { cn } from '@/lib/utils';
import type { HTMLAttributes } from 'vue';

const props = defineProps<{
  class?: HTMLAttributes['class'];
}>();
</script>

<template>
  <NumberFieldInput
    :class="
      cn(
        'flex h-10 w-full rounded-md border border-input bg-background px-8 py-2 text-sm text-center ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50',
        props.class,
      )
    "
  />
</template>
```

### System Info

```bash
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1
    Memory: 91.56 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.10.0/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.15.5 - ~/.nvm/versions/node/v20.10.0/bin/pnpm
  Browsers:
    Chrome: 125.0.6422.142
    Safari: 17.5
  npmPackages:
    @vueuse/core: ^10.11.0 => 10.11.0 
    radix-vue: ^1.8.3 => 1.8.3 
    vue: ^3.4.29 => 3.4.29
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

### PR DESCRIPTION
**Pull request by hsellik**
### 🔗 Linked issue

#613

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Change the NumberField, so it could be used in different configurations without extra effort from the developer. Resolves #613

### 📸 Screenshots (if appropriate)
Before:
image
image

After:
image
image

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by sadeghbarati** [comment]
@hsellik Thanks Man 🙌

Can you run `pnpm build:registry` in `apps/www`

**Comment by hsellik** [comment]
Oh, missed that one, pushed it now. The `pnpm build:registry` wants to remove empty lines at the end of the files for some reason, don't know if it's just my setup.

**Comment by sadeghbarati** [comment]
Will checkout to your branch tomorrow to push some changes if you don't mind 🙌


Cause using p-2.5 is not good imo

**Comment by sadeghbarati** [comment]
You were using the ring and focus stuff on **div** element in `NumberFieldContent.vue` which is not the best practice


The idea of `data-slot` is from tailwindui Catalyst template

**Pull request merged**
