### PR TITLE
docs: fix carousel scoped slots example

### PR DESCRIPTION
**Pull request by gigabites19**
### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Refs returned from scoped slots are not unwrapped, so value needs to be accessed manually

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by sadeghbarati** [comment]
in the `template` section refs are auto unwraped, so there is no need to `.value`

**Comment by gigabites19** [comment]
@sadeghbarati check it
https://stackblitz.com/edit/nuxt-starter-xegtw3

**Comment by sadeghbarati** [comment]
I'll push a fix

**Comment by sadeghbarati** [comment]
I'll push a fix

**Pull request closed without merging**
