### PR TITLE
docs: add `Input with Icon` Example

### LINKED ISSUE #341: [Feature]: Add icon in input component
### Describe the feature

Add an optional prop or slot that lets us add an icon to an input and control its positioning.

For example: https://ui.nuxt.com/components/input#icon

A prop seems difficult in vue-shadcn since the icon library is free to choose from, perhaps a slot is more suitable?

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

### PR DESCRIPTION
**Pull request by hrynevychroman**
This PR fix #341

### CODE REVIEW

**Comment by sadeghbarati** [comment]
Hey @romanhrynevych thanks!

You pushed additional `select.json` file too within this PR, I'll fix it

---

You way is simple and nice, although others wants something like 

- `beforeInput` - `afterInput`
- `leading` - `trailing`
- `startAdornment` - `endAdornment`

These can be `slots` or `props`


https://unaui.com/forms/input#slots

**Comment by hrynevychroman** [comment]
@sadeghbarati yeah, but Zernonia said that we can't modify original Input component, so how we can add this all Features?

**Comment by sadeghbarati** [comment]
> @sadeghbarati yeah, but Zernonia said that we can't modify original Input component, so how we can add this all Features?

Ow you right I thought we can have multiple components in one Vue file


But you can btw with 👇 

```vue
<script setup lang="(((tsx)))">

</script>

<template>...</template>
```

**Comment by hrynevychroman** [comment]
Never used tsx before, hahaha 😁

**Pull request merged**
