### PR TITLE
docs: add sub components example

### PR DESCRIPTION
**Pull request by Lol1chw**
### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Improves dx. Provides an example of how to make a component reusable.
Made changes to the passed component types to not be tied to a specific data model, now the type is based on a generic type.
Extended `tasks.json` for use in the example, the data for `tasks.json` is taken from DummyJSON.
Added a user to the schema for tasks.json.
Fixed filter-function type incompatibility in `examples/tasks/components/DataTableFacetedFilter.vue`

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by sadeghbarati** [comment]
Can you share an image or video about the PR changes, thanks

**Comment by Lol1chw** [comment]
Video:
https://github.com/radix-vue/shadcn-vue/assets/94941930/859f1e46-e080-4fd4-8f75-8084cf7f25bf

**Comment by Lol1chw** [comment]
Btw, I found the real reason related to the type incompatibility  in the filter-function of the `Command.vue` component. The generic type was not passed to the ComboboxRoot<T> type, so filter-function did not know what type it should expect.

So, if you pass in `Command.vue` a generic that inherits from the AcceptableValue type
` type AcceptableValue = string | number | boolean | Record<string, any>;`

```vue
<script setup lang="ts" generic="T extends string | number | boolean | Record<string, any>">
const props = withDefaults(defineProps<ComboboxRootProps<T> & { class?: HTMLAttributes['class'] }>(), {
  open: true,
})
```


then filter-function will automatically output the type for 'list':

image

This way we can get rid of the type predicate, which is always not completely type-safety.
We'll also reduce the amount of code.

**Comment by sadeghbarati** [comment]
@Lol1chw Thanks can you do the same thing to `Command.vue` in the default style and after that run `pnpm build:registry` in `apps/www`

By the way, types will be better in v2, and thanks for the fix

**Comment by Lol1chw** [comment]
My bad, I forgot about the `default` variant. Made changes to the default. 
Build was successful without errors.
image

**Comment by sadeghbarati** [comment]
I think showcasing `subRow` on Data Table page would be enough, thanks

**Pull request closed without merging**
