### PR TITLE
fix(cli): add `xl` item to borderRadius in tailwind.config template

### PR DESCRIPTION
**Pull request by itsTPM**
already did this in #231, but seems like a829212d4283d9312d6948bd979366706cf2b72d undid that

### CODE REVIEW

**Comment by sadeghbarati** [comment]
Sry that was a big refactor I did not notice that


not my quote `shadcn-svelte` issue section
> This project's goal is to remain aligned with [shadcn/ui](https://github.com/shadcn-ui/ui). If the feature you are requesting is not in the original shadcn/ui, it will not be considered here.


https://github.com/shadcn-ui/ui/blob/main/apps/www/registry/new-york/ui/card.tsx#L12

https://github.com/huntabyte/shadcn-svelte/blob/main/apps/www/src/lib/registry/new-york/ui/card/card.svelte#L13

**Comment by sadeghbarati** [comment]
I'll change those Card to use `default` style to keep the radius from Customize popup sound good?

**Comment by itsTPM** [comment]
customization popup changes the radius for the rounded-lg class, which is what the cards in shadcn-vue have (as i noticed), but you ofc can use a better solution, if there is such a thing

**Comment by itsTPM** [comment]
> Sry that was a big refactor I did not notice that
> 
> not my quote `shadcn-svelte` issue section
> 
> > This project's goal is to remain aligned with [shadcn/ui](https://github.com/shadcn-ui/ui). If the feature you are requesting is not in the original shadcn/ui, it will not be considered here.
> 
> https://github.com/shadcn-ui/ui/blob/main/apps/www/registry/new-york/ui/card.tsx#L12
> 
> https://github.com/huntabyte/shadcn-svelte/blob/main/apps/www/src/lib/registry/new-york/ui/card/card.svelte#L13

this issue seems to exist in shadcn-svelte as well, if shadcn-svelte also uses `rounded-ld` class for customizing border-radius (or for react shadcn too, i'll check this later)

**Comment by sadeghbarati** [comment]
@itsTPM

I think we must add another option to our tailwind.config `xl` 

https://github.com/shadcn-ui/ui/blob/main/tailwind.config.cjs#L52

You can add it here 👇 
https://github.com/radix-vue/shadcn-vue/blob/dev/packages/cli/src/utils/templates.ts#L119

**Comment by itsTPM** [comment]
yes, that's the point
thanks!

**Comment by sadeghbarati** [comment]
@itsTPM since you are in `dev` branch I can't checkout to yours cause I already have dev branch

Can you add same thing to this file in `apps/www`, Thanks 👍 
https://github.com/radix-vue/shadcn-vue/blob/dev/apps/www/tailwind.config.js#L52

**Comment by sadeghbarati** [comment]
Will fix [themes route cards](https://www.shadcn-vue.com/themes.html) after this, Thanks for bringing it up

**Pull request merged**
