### PR TITLE
fix(Button): add svg classnames to new york style

### LINKED ISSUE #871: [Bug]: Button missing svg classnames
### Reproduction

Use any icon with button and it will appear that the icon is larger than intended

### Describe the bug

The button component is misisng the following classnames: `[&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0`

### System Info

```bash
System:
    OS: macOS 15.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 70.55 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.3.0 - ~/Library/pnpm/node
    npm: 10.8.1 - ~/Library/pnpm/npm
    pnpm: 9.4.0 - ~/Library/pnpm/pnpm
    Watchman: 2024.10.07.00 - /opt/homebrew/bin/watchman
  Browsers:
    Edge: 130.0.2849.80
    Safari: 18.0
  npmPackages:
    @vueuse/core: ^11.2.0 => 11.2.0 
    radix-vue: ^1.9.9 => 1.9.9 
    vue: ^3.4.27 => 3.4.34
```

### Contributes

- [X] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

### PR DESCRIPTION
**Pull request by brianle1301**
### 🔗 Linked issue

Closes #871

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Adds svg classnames to the New York style button. The Default style already had these classnames. This ensures icons are of the correct size when placed inside buttons.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by sadeghbarati** [comment]
Could you please do it for the `default` style

Also, run build:registry in apps/www directory

**Comment by brianle1301** [comment]
@sadeghbarati The default already has these classnames. And sure, I can do a build

**Comment by brianle1301** [comment]
@sadeghbarati Running build:registry seems to remove all the final new lines of the json outputs. Is this expected?

(Only the color and index ones I might add)

**Comment by sadeghbarati** [comment]
I'll check. Thanks 🙌

**Comment by sadeghbarati** [comment]
Checked the main `shadcn-ui` and brought those updated classes here

- https://github.com/shadcn-ui/ui/blob/main/apps/www/registry/default/ui/button.tsx
- https://github.com/shadcn-ui/ui/blob/main/apps/www/registry/new-york/ui/button.tsx

**Pull request merged**
