### PR TITLE
fix: Input `attrs` not reactive

### LINKED ISSUE #224: [Bug]: Input `attrs` are not reactive
### Environment

```bash
Developement/Production OS: Windows 10 Pro 10.0.19045
Node version: 18.14.0
Package manager: pnpm@8.12.1
Radix Vue version: 1.2.5
Shadcn Vue version: 0.8.5
Vue version: 3.3.13
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.4.0
Client OS: Windows 10 Pro 10.0.19045
Browser: Chrome 120.0.6099.130
```

### Link to minimal reproduction

https://stackblitz.com/edit/8qmftg?file=src%2FApp.vue

### Steps to reproduce

1. Start a new Vue 3, Typescript project with Vite and create-vue `pnpm create vue@latest`.
2. Install tailwindcss and its peer dependencies.
3. After that Run the shadcn-vue init command to setup shadcn-vue in project. `pnpm dlx shadcn-vue@latest init`.
4. Install Input component from shadcn-vue. `pnpm dlx shadcn-vue@latest add input`.
5. Start the local dev server. `pnpm run dev`.
6. Create basic form in `App.vue` component with Input component from `shadcn-vue` and create password input so when we click on it it changes the type attribute of input tag.
```vue
<script setup lang="ts">
import { ref } from 'vue';
import { Input } from '@/components/ui/input';
import { cn } from '@/lib/utils';
import { EyeIcon, EyeOffIcon } from 'lucide-vue-next';

const showPassword = ref(false);
</script>

<template>
  <form>
     ...
    <div class="relative">
      <Input
        placeholder="Enter password"
        :type="showPassword ? 'text' : 'password'"
      />
      <button
        type="button"
        class="absolute right-0 top-1/2 -translate-y-1/2 p-3"
        @click="showPassword = !showPassword"
      >
        <EyeIcon v-if="showPassword" class="h-4 w-4" />
        <EyeOffIcon v-else class="h-4 w-4" />
      </button>
    </div>
  </form>
</template>
```

### Describe the bug

Yesterday, I was playing around with the `shadcn-vue` package for a little side project that I was building. I needed a password input for the signin/signup form. I added the input component from `shadcn-vue` and imported it into my form. I also needed a toggle button in the password input so that when the user clicks on it, it switches from type="password" to type="text" and vice versa. So, I implemented a basic form with a password input, and when I click on it, it toggles the `type`.

```vue
<script setup lang="ts">
import { ref } from 'vue';
import { Input } from '@/components/ui/input';
import { cn } from '@/lib/utils';
import { EyeIcon, EyeOffIcon } from 'lucide-vue-next';

const showPassword = ref(false);
</script>

<template>
  <form>
    ...
    <div class="relative">
      <Input
        placeholder="Enter password"
        :type="showMyPassword ? 'text' : 'password'"
      />
      <button
        type="button"
        class="absolute right-0 top-1/2 -translate-y-1/2 p-3"
        @click="showMyPassword = !showMyPassword"
      >
        <EyeIcon v-if="showMyPassword" class="h-4 w-4" />
        <EyeOffIcon v-else class="h-4 w-4" />
      </button>
    </div>
  </form>
</template>
```
But this was not working when i clicked on toggle button it was not toggling the type attribute on input. I was not able to figure out why its not working because the icon was changing but why `type` attribute is not changing?.

Then i checked the code of Input component and i found that we are using vue `useAttrs()` composable and grabbing all attributes destructuring the `class` and `rest` from it and adding to our `input` tag. 

```vue
<script setup lang="ts">
import { useAttrs } from 'vue'
import { useVModel } from '@vueuse/core'
import { cn } from '@/utils'

defineOptions({
  inheritAttrs: false,
})

const props = defineProps<{
  defaultValue?: string | number
  modelValue?: string | number
}>()

const emits = defineEmits<{
  (e: 'update:modelValue', payload: string | number): void
}>()

const { class: className, ...rest } = useAttrs()  // here we are destructuring attrs

const modelValue = useVModel(props, 'modelValue', emits, {
  passive: true,
  defaultValue: props.defaultValue,
})
</script>

<template>
  <input v-model="modelValue" :class="cn('flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50', className ?? '')" v-bind="rest">
</template>

```

When we destructure the attrs we looses the reactivity and that's why the attribute was not changing.

### Expected behavior

The Expected behavior is attrs should be reactive. When it changes it also updates the input attributes.

### Solution

We can solve this by using `computed` property. Here is the code for it.

```vue
<script setup lang="ts">
import { useAttrs, computed } from "vue";
import { useVModel } from "@vueuse/core";
import { cn } from "~/lib/utils";

defineOptions({
  inheritAttrs: false,
});

const props = defineProps<{
  defaultValue?: string | number;
  modelValue?: string | number;
}>();

const emits = defineEmits<{
  (e: "update:modelValue", payload: string | number): void;
}>();

const rawAttrs = useAttrs();

// using computed property
const attrs = computed(() => {
  const { class: className, ...rest } = rawAttrs;

  return { className, rest };
});

const modelValue = useVModel(props, "modelValue", emits, {
  passive: true,
  defaultValue: props.defaultValue,
});
</script>

<template>
  <input
    v-model="modelValue"
    :class="cn('flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50', attrs.className ?? '')"
    v-bind="attrs.rest"
  />
</template>
```

### Conext & Screenshots (if applicable)

Demo showing that after changing to `computed` property it is working.

[shadcn-vue-input-demo.webm](https://github.com/radix-vue/shadcn-vue/assets/62164346/26d18891-92d0-4581-ba40-10cd03d56a11)

### PR DESCRIPTION
**Pull request by ParasSolanki**
Fixes: #224

### CODE REVIEW

**Comment by ParasSolanki** [comment]
Do i have to run `pnpm build:registry` command?
I am using Windows laptop so seeing inconsistency in registry output. #181

**Comment by sadeghbarati** [comment]
No, no need to build the registry on your end

**Comment by sadeghbarati** [comment]
I have thought about `props` and `attrs`. Please share your thoughts, too 🙏 
 

--- 

#### attrs way

I think making read-only Proxy (useAttrs, $attrs) reactive is not a good idea 


We are using computed or maybe toRefs for attrs to make them reactive/can-be-mutated inside the Component, which they can't, we are changing their nature (readonly)

---

#### props way

By adding class to props, class will be removed from $attrs object so we will not get duplicated class so we can use props.class in cn function and v-bind="$attrs" without worrying about duplication 

Even though we are not changing/mutating some props like class (toRefs/computed) inside the Component 

I think using props is a better way. 

Sorry for my bad English. I'll try to make a Vue SFC Playground example to explain what I meant

https://github.com/radix-vue/shadcn-vue/issues/35

**Comment by ParasSolanki** [comment]
Yeah i also think using Props is a better approach here. Created a playground for it. 

[Vue SFC Playground](https://play.vuejs.org/#eNp9VW1v2zYQ/is3ooBcILTTBPuiOcm6osA6YFuwFe0XfahMnWwmFMnyxXbg+r/3SMmK46b5ZN37w7t7zjv21trpOiIr2dwLJ20AjyHa60rLzhoXYAcOW9hD60wHBbkWo+mDtjEMhuksSylX8VulKy2M9gE6v4SrlGFSsT9RKQOfjVNNxV4fPPzKbG5r7zfGNYNrWyuP5DCf9ZAIDAkBO6vqgCQBzFdvrne7nH6/n89Iytoe0Zp3pkF1VTGyVwwoTODKqAYd6b5ukHRleLBI0pPyN1AE3IYCSijsoCwqllIDlEKRikK+bKRSXJvAF8hr3kSrpCBgPDtw2fIHE7nU3qII9EuQOCrsUAd4tTstmORccCUbLPZfCNusf8wihmA0/C4o/f0p1Cv45ViuWGrHSe6KpZzpsfSZbPSZutUnpiLz2VFTK83OWPA0lVYup3feaFqKXUJSMWE6KxW6f22QNLWKlZAtyVbTVDd/ZV1wEc8OerFCcf+M/s5vk65itw49ujUBHG2hdksMvfn9///QLI6MNNSoyPsF43/ojYoJY+/2R9QNwT7yy2g/5P2VevnRv98G1P7wqAQ0ee6zf8Vom9+98PRHuJfTyxxX6T11caTCKa1A1XpJowyUh1reYCs1DpknOa3UK3QyvA3B+RIyEwjLnthwIIx1xnqafx98m6R5DiVFHVX4VKuINyX44OiF8A107BbUA/LItPiJPb84b/Boo7rXk1x5pPOYYATwd1JNikdLkSPaqEV6Fgg9mU6nQvnXfd8c9cGRWvnpnZF6UkAKoMa9xPZMomNej9V+YCfVK1qFW1jxN+ew4W1UCpyhRcCGdw0siBvohp+enbBY8kUt7pfZDeyWX4J94BeQjgH3HaRmcNO2NMNjx5b2ohwSnQ/SkgdXE/Vrl+iedYcsWWiNDrzDRsbu+C71Tl0MBLI1Dg8VjIier6WXC4o1MSjqOJ0ejSemjPDiOWUe8jP64TkX0Ehfk7YpRXTeuHzYMkuwebQZWwsZHviv58VZv4E0Umo43NAJowEOU1jzhdQNTeFVnRZ4uGV5hPb6XQog9uyeJEgHKf3dZJe09pLOE/Z+fZbR5cm5YvvvENRX7g==)

Sorry for the late response.

**Comment by sadeghbarati** [comment]
Just changed one thing in your playground, also thanks for your comment

[Vue SFC Playground](https://play.vuejs.org/#eNp9VVtv00oQ/itzLCQHqZuUVufFJ20PByHBEZcKEDxgJJz12Nl2vbvsJUkV8t+ZXTuXhtKneGa+mfl2bllnz40ZLwJmRTZ13ArjwaEP5rJUojPaeliDxQY20FjdQU7QfGd6rUzwg2E8SVKMlf9TqlJxrZyHzrVwESOMyuwVSqnhi7ayLrOnW4Sb6+V15dxS23qANpV0SIDppKdEZEjw2BlZeSQJYDp/drlep/CbzXRCUtL2jBas0zXKizIje5kBuXGca1mjJd2PJZKu8HcGSbqX/gpyjyufQwG5GZR5mcXQAAWXpCKX70shJVPasxmyitXBSMGJGEsAJhp2pwMTyhnknn6JEkOJHSoPT9bHCaOcEs5FjfnmO3Gb9I+ZBe+1gn85hb89pnoBfx3KZRbLcRS7zGLM+Fj6jDb6jNXqA1OS6eSgqKXKTjLvqCuNaMc3TisainVkUmZcd0ZItO+NF9S1MisgWaKtoq4u/086bwOebPV8jvz2Af2NW0VdmV1bdGgXRHBn85Vt0ffmlx/fUS8OjNTUIAn9iPEDOi1D5NjD/guqJtoHuMT2dZpfodpP7uXKo3LbR0WiEblJ+DKjaX7xyNP3dM/H58mvVBuq4m4VjtcKZKVaaqWnOPsVi6NIe/bq09s3z723gvqD7mjlamyEwoHEKDEQao5W+OjiCkhLQ7Q3tDjb3TJWG0ej0jtfR2maXElRBek/VzLgVQGOkqoWfoIK3YzKRYi0QX+wp+KkYSfbfdZf86TPvxGRy1GisjsFu4g7Rm+japTvLXnyaILi8Z3A1Wg8HnPpnvY1t1RDS2rpxjdaqFEO0YGK/tilSAt4eBN22X7bbMqXNxJXMGfPTmHJmiAlWE1DhDXrapjRXqEdfvrNhlnLZhW/bRMMzIqdg7ljZxAPCXMdxMox3TTU/0NgQzNVDIFOB6ll3lZ0NiobT0XSbaMkodHKsw5rEbrDm9aDOip/zRptcZtB8+DYQjgxI18dvKSK09lSeGRKDM8eUqauP6AfnnMGtXAVaeuCB+u0TUcxbRjWe5s2FRf+jv19mp/0I0ktpYLDFZ0/auDQhQWbCVVTF55UcaKHO5haaC5fRAfavPW9APGYxb+qBNkPYcL1UXaQe6cu2/wCaYFtXA==)


Let's **fake imagine** class type changes in the feature so using this type from Vue (`HTMLAttributes['class']`) will save us refactoring tons of Components Props

```diff
- class?: string
+ class?: HTMLAttributes['class']
```

**Comment by ParasSolanki** [comment]
Yeah this is right way to do the typing. I should've used the HTMLAttributes['class'].

**Comment by ParasSolanki** [comment]
Now, Should i change my implementation to using Props for class? Or there are still some scenarios or edge cases we want to check first?

**Comment by sadeghbarati** [comment]
Yes, go with Props 

Please, if you have time, refactor all the components

**Comment by ParasSolanki** [comment]
Yeah, okay.
And by all you mean FormItem, PaginationEllipsis and other components where we are using useAttrs for class?

**Comment by sadeghbarati** [comment]
Yes, only useAttrs 🙏

I'll refactor the rest if it's needed

**Comment by ParasSolanki** [comment]
Change the implementation to using props for `class`. Let me know if there are any other issue.

**Pull request merged**
