### PR TITLE
fix: sidebar component mobile #840

### LINKED ISSUE #840: [Bug]: Sidebar Mobile
### Reproduction

N/A 

### Describe the bug

there are two mobile fixes i did in my own src but 

https://github.com/unovue/shadcn-vue/blob/52b9b20b3c128287c81e7c83757494a5c6531275/apps/www/src/lib/registry/default/ui/sidebar/SidebarProvider.vue#L21

```
const isMobile = useMediaQuery("(max-width: 768px)");
```

and 

https://github.com/unovue/shadcn-vue/blob/52b9b20b3c128287c81e7c83757494a5c6531275/apps/www/src/lib/registry/default/ui/sidebar/SidebarProvider.vue#L42

```
function toggleSidebar() {
  return isMobile.value
    ? setOpenMobile(!openMobile.value)
    : setOpen(!open.value);
}
```

### System Info

```bash
N/A
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

### PR DESCRIPTION
**Pull request by Whbbit1999**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [x] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Resolves #840 

Sorting out the solution in #840.

Now you can add the sidebar part in tailwindcss.config.js, but I don’t know how to add the sidebar variable in the css file😓

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by carlospccarvalho** [comment]
I need this pr @zernonia

**Comment by zernonia** [comment]
Thanks for the fix @Whbbit1999 !!! Can we update `new-york` style for these as well? 😁

**Comment by Whbbit1999** [comment]
I think you can update.Now the sidebar css variables  I haven't been able to integrate it into the cli.

**Comment by Whbbit1999** [comment]
The current changes should only affect the Sidebar Component.

**Pull request merged**
