### PR TITLE
fix: sidebar-provider imports

### LINKED ISSUE #928: [Bug]: sidebar imports missing
### Reproduction

npx add shadcn@latest sidebar

### Describe the bug

The problem is on executing the command npx shadcn@latest add sidebar the sidebar requires the ùseMediaQuery import

Browser
```
Uncaught (in promise) ReferenceError: useMediaQuery is not defined
```

Inside VSCODE with TS-Plugin:
```bash
Cannot find name 'useMediaQuery'.ts-plugin(2304)
```

### System Info

Windows Version 10.0.19045 Build 19045
Firefox Developer; 133.0

### Contributes

- [X] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

### PR DESCRIPTION
**Pull request by fabianbernhart**
### 🔗 Linked issue

#928 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)

- [x]  🐞 Bug fix (a non-breaking change that fixes an issue)

- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

The problem is on executing the command `npx shadcn@latest add sidebar ` the sidebar requires the `ùseMediaQuery` so i added the import from `@vueuse/core`

This change is required because of import errors. _it crashes_

Resolves #928 

### 📸 Screenshots (if appropriate)

Screenshot of the error in IDE

grafik

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by fabianbernhart** [comment]
Is there a documentation required for imports?

**Comment by pushpak1300** [comment]
can we merge this ?

**Comment by sadeghbarati** [comment]
Sry it takes 5 days to merge

**Comment by pushpak1300** [comment]
No worries @sadeghbarati you are doing great job 👍🏻

**Pull request merged**
